# awal fungsi reset
def reset():
    textStruk.delete(1.0,END)
    e_KrabbyPatty.set('0')
    e_KrabbyPattySeaCheese.set('0')
    e_DoubleKrabbyPatty.set('0')
    e_TripleKrabbyPatty.set('0')
    e_KrabbyMeal.set('0')
    e_DoubleKrabbyMeal.set('0')
    e_SailorsSurprise.set('0')
    e_SaltySeaDog.set('0')
    e_FootLong.set('0')

    e_KelpShake .set('0')
    e_SmallSeafoamSoda.set('0')
    e_MediumSeafoamSoda.set('0')
    e_LargeSeafoamSoda.set('0')

    e_CoralBits.set('0')
    e_LargeCoralBits.set('0')
    e_KelpRings.set('0')
    e_SaltySauce.set('0')
    e_KrabbyFries.set('0')
    e_SeaweedSalad.set('0')
    # batas untuk variables

    textKrabbyPatty.config(state=DISABLED)
    textKrabbyPattySeaCheese.config(state=DISABLED)
    textDoubleKrabbyPatty.config(state=DISABLED)
    textTripleKrabbyPatty.config(state=DISABLED)
    textKrabbyMeal.config(state=DISABLED)
    textDoubleKrabbyMeal.config(state=DISABLED)
    textSailorsSurprise.config(state=DISABLED)
    textSaltySeaDog.config(state=DISABLED)
    textFootLong.config(state=DISABLED)

    textKelpShake .config(state=DISABLED)
    textSmallSeafoamSoda.config(state=DISABLED)
    textMediumSeafoamSoda.config(state=DISABLED)
    textLargeSeafoamSoda.config(state=DISABLED)

    textCoralBits.config(state=DISABLED)
    textLargeCoralBits.config(state=DISABLED)
    textKelpRings.config(state=DISABLED)
    textSaltySauce.config(state=DISABLED)
    textKrabbyFries.config(state=DISABLED)
    textSeaweedSalad.config(state=DISABLED)

    var1.set(0)
    var2.set(0)
    var3.set(0)
    var4.set(0)
    var5.set(0)
    var6.set(0)
    var7.set(0)
    var8.set(0)
    var9.set(0)
    var10.set(0)
    var11.set(0)
    var12.set(0)
    var13.set(0)
    var14.set(0)
    var15.set(0)
    var16.set(0)
    var17.set(0)
    var18.set(0)
    var19.set(0)
    var20.set(0)
    var21.set(0)
    var22.set(0)
    var23.set(0)
    var24.set(0)
    var25.set(0)
    var26.set(0)
    var27.set(0)

    hargadariDrinksvar.set('')
    hargadariMealsDealsvar.set('')
    hargadariSeadSidesvar.set('')
    subtotalvar.set('')
    servicetaxvar.set('')
    totalcostvar.set('')
    taxvaluevar.set('')

# batas fungsi reset
