from tkinter import *

# VARIABLE
# Menentukan variables
var1=IntVar()
var2=IntVar()
var3=IntVar()
var4=IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11 = IntVar()
var12 = IntVar()
var13 = IntVar()
var14 = IntVar()
var15 = IntVar()
var16 = IntVar()
var17 = IntVar()
var18 = IntVar()
var19 = IntVar()
var20 = IntVar()
var21 = IntVar()
var22 = IntVar()
var23 = IntVar()
var24 = IntVar()
var25 = IntVar()
var26 = IntVar()
var27 = IntVar()

# variabel menuiMealsDealshargadariMealsDeals
e_KrabbyPatty=StringVar()
e_KrabbyPattySeaCheese=StringVar()
e_DoubleKrabbyPatty = StringVar()
e_TripleKrabbyPatty = StringVar()
e_KrabbyMeal = StringVar()
e_DoubleKrabbyMeal = StringVar()
e_SailorsSurprise = StringVar()
e_SaltySeaDog = StringVar()
e_FootLong = StringVar()

# variabel menu Drinks
e_KelpShake =StringVar()
e_SmallSeafoamSoda = StringVar()
e_MediumSeafoamSoda = StringVar()
e_LargeSeafoamSoda = StringVar()

# variabel menu SeadSideshargadariSeadSides
e_CoralBits=StringVar()
e_LargeCoralBits = StringVar()
e_KelpRings = StringVar()
e_SaltySauce = StringVar()
e_KrabbyFries = StringVar()
e_SeaweedSalad = StringVar()

# variabel Harga dalam struk
hargadariMealsDealsvar=StringVar()
hargadariDrinksvar=StringVar()
hargadariSeadSidesvar=StringVar()
subtotalvar=StringVar()
servicetaxvar=StringVar()
totalcostvar=StringVar()
taxvaluevar=StringVar()

e_KrabbyPatty.set('0')
e_KrabbyPattySeaCheese.set('0')
e_DoubleKrabbyPatty.set('0')
e_TripleKrabbyPatty.set('0')
e_KrabbyMeal.set('0')
e_DoubleKrabbyMeal.set('0')
e_SailorsSurprise.set('0')
e_SaltySeaDog.set('0')
e_FootLong.set('0')

e_KelpShake .set('0')
e_SmallSeafoamSoda.set('0')
e_MediumSeafoamSoda.set('0')
e_LargeSeafoamSoda.set('0')

e_CoralBits.set('0')
e_LargeCoralBits.set('0')
e_KelpRings.set('0')
e_SaltySauce.set('0')
e_KrabbyFries.set('0')
e_SeaweedSalad.set('0')


# VARIABLE
# Menentukan variables
var1=IntVar()
var2=IntVar()
var3=IntVar()
var4=IntVar()
var5 = IntVar()
var6 = IntVar()
var7 = IntVar()
var8 = IntVar()
var9 = IntVar()
var10 = IntVar()
var11 = IntVar()
var12 = IntVar()
var13 = IntVar()
var14 = IntVar()
var15 = IntVar()
var16 = IntVar()
var17 = IntVar()
var18 = IntVar()
var19 = IntVar()
var20 = IntVar()
var21 = IntVar()
var22 = IntVar()
var23 = IntVar()
var24 = IntVar()
var25 = IntVar()
var26 = IntVar()
var27 = IntVar()

# variabel menuiMealsDealshargadariMealsDeals
e_KrabbyPatty=StringVar()
e_KrabbyPattySeaCheese=StringVar()
e_DoubleKrabbyPatty = StringVar()
e_TripleKrabbyPatty = StringVar()
e_KrabbyMeal = StringVar()
e_DoubleKrabbyMeal = StringVar()
e_SailorsSurprise = StringVar()
e_SaltySeaDog = StringVar()
e_FootLong = StringVar()

# variabel menu Drinks
e_KelpShake =StringVar()
e_SmallSeafoamSoda = StringVar()
e_MediumSeafoamSoda = StringVar()
e_LargeSeafoamSoda = StringVar()

# variabel menu SeadSideshargadariSeadSides
e_CoralBits=StringVar()
e_LargeCoralBits = StringVar()
e_KelpRings = StringVar()
e_SaltySauce = StringVar()
e_KrabbyFries = StringVar()
e_SeaweedSalad = StringVar()

# variabel Harga dalam struk
hargadariMealsDealsvar=StringVar()
hargadariDrinksvar=StringVar()
hargadariSeadSidesvar=StringVar()
subtotalvar=StringVar()
servicetaxvar=StringVar()
totalcostvar=StringVar()
taxvaluevar=StringVar()

e_KrabbyPatty.set('0')
e_KrabbyPattySeaCheese.set('0')
e_DoubleKrabbyPatty.set('0')
e_TripleKrabbyPatty.set('0')
e_KrabbyMeal.set('0')
e_DoubleKrabbyMeal.set('0')
e_SailorsSurprise.set('0')
e_SaltySeaDog.set('0')
e_FootLong.set('0')

e_KelpShake .set('0')
e_SmallSeafoamSoda.set('0')
e_MediumSeafoamSoda.set('0')
e_LargeSeafoamSoda.set('0')

e_CoralBits.set('0')
e_LargeCoralBits.set('0')
e_KelpRings.set('0')
e_SaltySauce.set('0')
e_KrabbyFries.set('0')
e_SeaweedSalad.set('0')
